services:
  mcp-server:
    build: /mnt/apps/apps/mcp-server/game-mcp-server/mcp
    container_name: mcp-server
    ports:
      - "5356:3000"
    environment:
      - QDRANT_URL=http://192.168.66.3:6333
      - EMBEDDING_URL=http://192.168.66.3:5361
      - NEO4J_URL=bolt://192.168.66.3:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-secure-password
      - GRAPH_COLLECTION=code_graph
      - NODE_ENV=production
    volumes:
      - /mnt/apps/apps/mcp-server/game-mcp-server/mcp/config:/app/config
    restart: unless-stopped

  graph-builder:
    build: /mnt/apps/apps/mcp-server/game-mcp-server/graph-builder
    container_name: graph-builder
    ports:
      - "5346:4100"
    environment:
      - REPO_PATH=/repo
      - STAGING_PATH=/staging
      - REPO_URL=https://github.com/chris-arsenault/genai-game-engine.git
      - REPO_BRANCH=main
      - GRAPH_BUILDER_PORT=4100
      - NEO4J_URL=bolt://192.168.66.3:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-secure-password
      - QDRANT_URL=http://192.168.66.3:6333
      - EMBEDDING_URL=http://192.168.66.3:5361
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-5
      - LOG_LEVEL=info
    volumes:
      - /mnt/apps/apps/mcp-server/graph-repo:/repo
      - /mnt/apps/apps/mcp-server/graph-staging:/staging
      - /mnt/apps/apps/mcp-server/game-mcp-server/graph-builder/config:/app/config
    restart: unless-stopped

  backlog-editor:
    build: /mnt/apps/apps/mcp-server/game-mcp-server/backlog-editor
    container_name: backlog-editor
    ports:
      - "5365:4005"
    environment:
      - PORT=4005
      - QDRANT_URL=http://192.168.66.3:6333
      - EMBEDDING_URL=http://192.168.66.3:5361
      - BACKLOG_COLLECTION=backlog_items
      - HANDOFF_COLLECTION=handoff_notes
      - HANDOFF_ID=11111111-1111-1111-1111-111111111111
      - GRAPH_COLLECTION=code_graph
      - NEO4J_HTTP_URL=http://192.168.66.3:7474
      - NEO4J_DATABASE=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-secure-password
      - GRAPH_MAX_DEPTH=3
    restart: unless-stopped
