version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - /mnt/apps/apps/mcp-server/qdrant-storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - mcp-network

  embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: embedding-service
    environment:
      - MODEL_ID=nomic-ai/nomic-embed-text-v1.5
      - REVISION=main
      - MAX_BATCH_SIZE=32
      - MODEL_CACHE=/data
    volumes:
      - /mnt/apps/apps/mcp-server/embedding-cache:/data
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-server:
    build: /mnt/apps/apps/mcp-server/game-mcp-server
    container_name: mcp-server
    ports:
      - "5356:3000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_URL=http://embedding-service:80
      - NODE_ENV=production
    volumes:
      - /mnt/apps/apps/mcp-server/game-mcp-server/config:/app/config
    depends_on:
      - qdrant
      - embedding-service
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
