version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - /mnt/apps/apps/mcp-server/qdrant-storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - mcp-network
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j
    volumes:
      - /mnt/apps/apps/mcp-server/neo4j_data:/data
      - /mnt/apps/apps/mcp-server/neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/your-secure-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_max__size=2G
    restart: unless-stopped
    networks:
      - mcp-network

  embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: embedding-service
    environment:
      - MODEL_ID=nomic-ai/nomic-embed-text-v1.5
      - REVISION=main
      - MAX_BATCH_SIZE=32
      - MODEL_CACHE=/data
    volumes:
      - /mnt/apps/apps/mcp-server/embedding-cache:/data
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-server:
    build: /mnt/apps/apps/mcp-server/game-mcp-server/mcp
    container_name: mcp-server
    ports:
      - "5356:3000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_URL=http://embedding-service:80
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-secure-password
      - GRAPH_COLLECTION=code_graph
      - NODE_ENV=production
    volumes:
      - /mnt/apps/apps/mcp-server/game-mcp-server/config:/app/config
    depends_on:
      - qdrant
      - embedding-service
    restart: unless-stopped
    networks:
      - mcp-network
  graph-builder:
    build: ./graph-builder
    container_name: graph-builder
    ports:
      - "4100:4100"
    environment:
      - REPO_PATH=/repo
      - STAGING_PATH=/staging
      - GRAPH_BUILDER_PORT=4100
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-secure-password
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_URL=http://embedding-service:80
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-5}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0}
      - LOG_LEVEL=info
    volumes:
      - /mnt/tank/your-game-repo:/repo:ro        # Mount game repo read-only
      - /mnt/tank/mcp-stack/graph-staging:/staging
      - /mnt/tank/mcp-stack/graph-builder/config:/app/config
    depends_on:
      - neo4j
      - qdrant
      - embedding-service
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
